-- Olá, sejam_bem vindos
-- Vamos criar nosso banco de dados e organizar o nosso codigo SEM ESPECIFICAR CONSTRAINTS E FK

SHOW DATABASES;
CREATE DATABASE Oficina_DIO;
USE Oficina_DIO;

CREATE TABLE CLIENTE(
    IdCliente INT PRIMARY KEY AUTO_INCREMENT,
    Primeiro_Nome VARCHAR(20) NOT NULL,
    Sobrenome VARCHAR(55) NOT NULL,
    CPF CHAR(11) NOT NULL,
    Telefone_DDD CHAR(2) NOT NULL,
    Telefone CHAR(9) NOT NULL,
    Email VARCHAR(45),
    Endereco_Rua VARCHAR(45),
    Endereco_Numero INT,
    Endereco_Bairro VARCHAR(30),
    Endereco_Cidade VARCHAR(30),
    Endereco_Estado VARCHAR(30),
    CONSTRAINT Unique_CLIENTE_CPF UNIQUE(CPF)
);

CREATE TABLE EQUIPE_MECANICA(
    IdEquipe INT PRIMARY KEY AUTO_INCREMENT,
    Nome_Equipe VARCHAR(20) NOT NULL,
    Quantidade_Membros INT NOT NULL,
    Especialidade VARCHAR(20) DEFAULT 'Nao definido'
);

CREATE TABLE ORDEM_SERVICO(
    IdOrdem INT PRIMARY KEY AUTO_INCREMENT,
    Data_Inicio DATE NOT NULL,
    Previsao_Entrega DATE,
    Status ENUM('Pendente', 'Iniciado', 'Concluido'),
    EQUIPE_MECANICA_IdEquipe INT,
    CONSTRAINT FK_OS_EQUIPE_MEC_IdEquipe FOREIGN KEY(EQUIPE_MECANICA_IdEquipe) REFERENCES EQUIPE_MECANICA(IdEquipe)
);

CREATE TABLE CARRO(
    IdCarro INT PRIMARY KEY AUTO_INCREMENT,
    Marca VARCHAR(20) NOT NULL,
    Modelo VARCHAR(20) NOT NULL,
    Cor VARCHAR(20) NOT NULL,
    Ano DATE NOT NULL,
    Placa CHAR(7) NOT NULL,
    IdCliente INT,
    ORDEM_SERVICO_IdOrdem INT,
    ORDEM_SERVICO_EQUIPE_MECANICA_IdEquipe INT,
    CONSTRAINT Unique_CARRO_Placa UNIQUE(Placa),
    CONSTRAINT FK_CLIENTE_IdCliente FOREIGN KEY(IdCliente) REFERENCES CLIENTE(IdCliente),
    CONSTRAINT FK_CLIENTE_OS_IdOrdem FOREIGN KEY(ORDEM_SERVICO_IdOrdem) REFERENCES ORDEM_SERVICO(IdOrdem),
    CONSTRAINT FK_CLIENTE_OS_EQUIPE_MEC_IdEquipe FOREIGN KEY(ORDEM_SERVICO_EQUIPE_MECANICA_IdEquipe) REFERENCES EQUIPE_MECANICA(IdEquipe)
);

CREATE TABLE SERVICO(
    IdServico INT PRIMARY KEY AUTO_INCREMENT,
    Categoria_Servico ENUM('Revisao', 'Conserto', 'Troca') NOT NULL,
    Peca VARCHAR(45) NOT NULL,
    Nome_Servico VARCHAR(30) NOT NULL,
    Preco_Servico FLOAT NOT NULL,
    Duracao_Horas INT,
    ORDEM_SERVICO_IdOrdem INT,
    EQUIPE_MECANICA_IdEquipe INT,
    CONSTRAINT FK_SERVICO_OS_IdOrdem FOREIGN KEY (ORDEM_SERVICO_IdOrdem) REFERENCES ORDEM_SERVICO(IdOrdem),
    CONSTRAINT FK_SERVICO_EQUIPE_IdOrdem FOREIGN KEY (EQUIPE_MECANICA_IdEquipe) REFERENCES EQUIPE_MECANICA(IdEquipe)
);

CREATE TABLE FUNCIONARIO(
    IdFuncionario INT PRIMARY KEY AUTO_INCREMENT,
    Primeiro_Nome VARCHAR(20) NOT NULL,
    Sobrenome VARCHAR(45) NOT NULL,
    Cargo VARCHAR(20),
    Data_Contratacao DATE NOT NULL,
    EQUIPE_MECANICA_IdEquipe INT,
    CONSTRAINT FK_FUNCIONARIO_EQUIPE_IdEquipe FOREIGN KEY(EQUIPE_MECANICA_IdEquipe) REFERENCES EQUIPE_MECANICA(IdEquipe)
);

CREATE TABLE CARRO_FAZ_SERVICO(
    CARRO_IdCarro INT,
    SERVICO_idServico INT,
    SERVICO_Ordem_Servico_IdOrdem INT,
    PRIMARY KEY(CARRO_IdCarro, SERVICO_idServico),
    CONSTRAINT FK_FAZ_CARRO_IdCarro FOREIGN KEY(CARRO_IdCarro) REFERENCES CARRO(IdCarro),
    CONSTRAINT FK_FAZ_SERVICO_IdServico FOREIGN KEY(SERVICO_idServico) REFERENCES SERVICO(IdServico)
);